"""
Report Service — generate, store, and review compliance reports.
PDF generation uses ReportLab. Report approval requires electronic signature.
"""
import io
from datetime import datetime, date, timezone
from typing import Optional
from sqlalchemy import select, and_
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.compliance import ReportArchive, ReviewRecord


class ReportService:
    async def list_reports(
        self,
        db: AsyncSession,
        limit: int = 50,
    ) -> list[ReportArchive]:
        stmt = (
            select(ReportArchive)
            .order_by(ReportArchive.generated_at.desc())
            .limit(limit)
        )
        result = await db.execute(stmt)
        return list(result.scalars().all())

    async def get_report(self, db: AsyncSession, report_id: int) -> Optional[ReportArchive]:
        result = await db.execute(
            select(ReportArchive).where(ReportArchive.report_id == report_id)
        )
        return result.scalar_one_or_none()

    async def generate_report(
        self,
        db: AsyncSession,
        report_type: str,
        period_start: date,
        period_end: date,
        generated_by_user_id: int,
        generated_by_username: str,
    ) -> ReportArchive:
        pdf_bytes = await self._build_pdf(
            db, report_type, period_start, period_end, generated_by_username
        )

        title = f"{report_type.replace('_', ' ').title()} — {period_start} to {period_end}"
        report = ReportArchive(
            report_type=report_type,
            report_title=title,
            period_start=datetime.combine(period_start, datetime.min.time()).replace(tzinfo=timezone.utc),
            period_end=datetime.combine(period_end, datetime.max.time()).replace(tzinfo=timezone.utc),
            generated_at=datetime.now(timezone.utc),
            generated_by_user_id=generated_by_user_id,
            review_state='PENDING_REVIEW',
            pdf_content=pdf_bytes,
            file_size_bytes=len(pdf_bytes),
        )
        db.add(report)
        await db.flush()
        return report

    async def approve_report(
        self,
        db: AsyncSession,
        report: ReportArchive,
        approved_by_user_id: int,
        signature_id: int,
        comment: str,
    ) -> ReportArchive:
        report.review_state = 'APPROVED'
        report.approved_by_user_id = approved_by_user_id
        report.approval_signature_id = signature_id
        report.approved_at = datetime.now(timezone.utc)

        review = ReviewRecord(
            record_type='REPORT',
            record_id=str(report.report_id),
            review_state='APPROVED',
            reviewed_by_user_id=approved_by_user_id,
            signature_id=signature_id,
            review_comment=comment,
            reviewed_at=datetime.now(timezone.utc),
        )
        db.add(review)
        await db.flush()
        return report

    async def _build_pdf(
        self,
        db: AsyncSession,
        report_type: str,
        period_start: date,
        period_end: date,
        generated_by: str,
    ) -> bytes:
        """Generate a PDF using ReportLab. Returns PDF bytes."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib import colors
            from reportlab.lib.units import inch

            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []

            # Header
            story.append(Paragraph("IQ-RAD Radiation Monitoring System", styles['Title']))
            story.append(Paragraph(f"{report_type.replace('_', ' ').title()}", styles['Heading1']))
            story.append(Spacer(1, 0.2 * inch))

            meta = [
                ['Period:', f"{period_start} to {period_end}"],
                ['Generated:', datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')],
                ['Generated By:', generated_by],
                ['System:', 'IQ-RAD v1.0 — Ionetix PET Facility'],
                ['Compliance:', '21 CFR Part 11 / 21 CFR Part 212 / 10 CFR Part 20'],
            ]
            meta_table = Table(meta, colWidths=[1.5 * inch, 4 * inch])
            meta_table.setStyle(TableStyle([
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 0.3 * inch))

            # Summary note
            story.append(Paragraph(
                f"This report covers the period from {period_start} to {period_end}. "
                f"All data is sourced from the immutable normalized_readings historian. "
                f"This document is subject to review and approval per the IQ-RAD review workflow.",
                styles['Normal']
            ))
            story.append(Spacer(1, 0.2 * inch))

            # Fetch basic summary data
            from app.models.runtime import NormalizedReading
            from sqlalchemy import func
            start_dt = datetime.combine(period_start, datetime.min.time()).replace(tzinfo=timezone.utc)
            end_dt = datetime.combine(period_end, datetime.max.time()).replace(tzinfo=timezone.utc)

            summary_stmt = (
                select(
                    NormalizedReading.channel_id,
                    func.count(NormalizedReading.ingestion_id).label('count'),
                    func.min(NormalizedReading.normalized_value).label('min_val'),
                    func.max(NormalizedReading.normalized_value).label('max_val'),
                    func.avg(NormalizedReading.normalized_value).label('avg_val'),
                )
                .where(and_(
                    NormalizedReading.measured_at_utc >= start_dt,
                    NormalizedReading.measured_at_utc <= end_dt,
                ))
                .group_by(NormalizedReading.channel_id)
            )
            result = await db.execute(summary_stmt)
            rows = result.all()

            if rows:
                from app.models.master import Channel
                ch_ids = [r.channel_id for r in rows]
                ch_result = await db.execute(select(Channel).where(Channel.channel_id.in_(ch_ids)))
                ch_map = {c.channel_id: c for c in ch_result.scalars()}

                table_data = [['Channel', 'Readings', 'Min', 'Max', 'Avg']]
                for r in rows:
                    ch = ch_map.get(r.channel_id)
                    table_data.append([
                        ch.channel_code if ch else str(r.channel_id),
                        str(r.count),
                        f"{r.min_val:.4f}" if r.min_val is not None else '—',
                        f"{r.max_val:.4f}" if r.max_val is not None else '—',
                        f"{r.avg_val:.4f}" if r.avg_val is not None else '—',
                    ])

                t = Table(table_data, colWidths=[1.5 * inch, 1 * inch, 1 * inch, 1 * inch, 1 * inch])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
                ]))
                story.append(Paragraph("Channel Summary", styles['Heading2']))
                story.append(t)

            story.append(Spacer(1, 0.5 * inch))
            story.append(Paragraph(
                "CONFIDENTIAL — 21 CFR Part 11 Electronic Record — Do not distribute without authorization",
                styles['Normal']
            ))

            doc.build(story)
            return buffer.getvalue()

        except ImportError:
            # ReportLab not available; return minimal placeholder
            return (
                f"IQ-RAD Report\n{report_type}\n{period_start} to {period_end}\n"
                f"Generated by {generated_by}\n"
                "[ReportLab not installed — install reportlab for PDF generation]"
            ).encode()


report_service = ReportService()
